PRAGMA foreign_keys = ON;

CREATE TABLE creators (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('demo','active','paused')), domain TEXT, brand_json TEXT NOT NULL, agent_json TEXT NOT NULL, model_policy_json TEXT NOT NULL, monetization_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE creator_domains (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), hostname TEXT NOT NULL UNIQUE, verified_at TEXT);
CREATE TABLE creator_features (creator_id TEXT NOT NULL REFERENCES creators(id), feature TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, config_json TEXT NOT NULL DEFAULT '{}', PRIMARY KEY(creator_id,feature));
CREATE TABLE admin_users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, role TEXT NOT NULL CHECK(role IN ('owner','operator','analyst')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE content_sources (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), source_type TEXT NOT NULL, source_url TEXT, external_id TEXT, rights_status TEXT NOT NULL, ingestion_status TEXT NOT NULL DEFAULT 'idle', cursor TEXT, last_error TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(creator_id,source_type,external_id));
CREATE TABLE content_items (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), source_id TEXT REFERENCES content_sources(id), external_id TEXT, source_url TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, published_at TEXT, thumbnail_url TEXT, content_type TEXT NOT NULL, structured_json TEXT NOT NULL DEFAULT '{}', tags_json TEXT NOT NULL DEFAULT '[]', embedding_reference TEXT, processing_status TEXT NOT NULL DEFAULT 'ready', provenance_json TEXT NOT NULL, confidence REAL NOT NULL DEFAULT 1, rights_status TEXT NOT NULL CHECK(rights_status IN ('public_metadata','creator_authorized','creator_uploaded','licensed','AI_generated','unknown_rights')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(creator_id,source_id,external_id));
CREATE INDEX content_by_creator ON content_items(creator_id,processing_status);
CREATE TABLE content_tags (creator_id TEXT NOT NULL REFERENCES creators(id), content_id TEXT NOT NULL REFERENCES content_items(id), tag TEXT NOT NULL, PRIMARY KEY(creator_id,content_id,tag));
CREATE TABLE content_embeddings (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), content_id TEXT NOT NULL REFERENCES content_items(id), model TEXT NOT NULL, vector_id TEXT NOT NULL, checksum TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(creator_id,content_id,model));

CREATE TABLE agents (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), role TEXT NOT NULL, instructions TEXT NOT NULL, prompt_version TEXT NOT NULL, model_policy TEXT NOT NULL, memory_policy TEXT NOT NULL, safety_policy TEXT NOT NULL, max_tool_calls INTEGER NOT NULL DEFAULT 4, max_tokens INTEGER NOT NULL DEFAULT 1000, max_cost_usd REAL NOT NULL DEFAULT 0.05, enabled INTEGER NOT NULL DEFAULT 1);
CREATE TABLE agent_tools (creator_id TEXT NOT NULL REFERENCES creators(id), agent_id TEXT NOT NULL REFERENCES agents(id), tool_name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(creator_id,agent_id,tool_name));
CREATE TABLE ai_requests (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), agent_id TEXT, feature TEXT NOT NULL, task TEXT NOT NULL, policy TEXT NOT NULL, provider TEXT, model TEXT, status TEXT NOT NULL, latency_ms INTEGER, estimated_cost_usd REAL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ai_usage (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), request_id TEXT NOT NULL REFERENCES ai_requests(id), input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0, estimated_cost_usd REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE users (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), session_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(creator_id,session_hash));
CREATE TABLE user_preferences (creator_id TEXT NOT NULL REFERENCES creators(id), user_id TEXT NOT NULL REFERENCES users(id), preferences_json TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(creator_id,user_id));
CREATE TABLE plans (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), code TEXT NOT NULL, label TEXT NOT NULL, price_json TEXT NOT NULL DEFAULT '{}', active INTEGER NOT NULL DEFAULT 1, UNIQUE(creator_id,code));
CREATE TABLE entitlements (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), code TEXT NOT NULL, description TEXT NOT NULL, UNIQUE(creator_id,code));
CREATE TABLE feature_gates (creator_id TEXT NOT NULL REFERENCES creators(id), feature TEXT NOT NULL, required_entitlement TEXT, free_usage_limit INTEGER, reset_period TEXT, trial_usage INTEGER NOT NULL DEFAULT 0, paywall_placement TEXT, enabled INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(creator_id,feature));
CREATE TABLE usage_limits (creator_id TEXT NOT NULL REFERENCES creators(id), user_id TEXT NOT NULL REFERENCES users(id), feature TEXT NOT NULL, period_key TEXT NOT NULL, used INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(creator_id,user_id,feature,period_key));
CREATE TABLE user_entitlements (creator_id TEXT NOT NULL REFERENCES creators(id), user_id TEXT NOT NULL REFERENCES users(id), entitlement_code TEXT NOT NULL, provider TEXT NOT NULL, external_reference TEXT, expires_at TEXT, PRIMARY KEY(creator_id,user_id,entitlement_code));

CREATE TABLE meal_plans (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), user_id TEXT NOT NULL REFERENCES users(id), days INTEGER NOT NULL, family_size INTEGER NOT NULL, preferences_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE meal_plan_items (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), meal_plan_id TEXT NOT NULL REFERENCES meal_plans(id), day_number INTEGER NOT NULL, meal_type TEXT NOT NULL, content_id TEXT NOT NULL REFERENCES content_items(id), servings INTEGER NOT NULL, UNIQUE(creator_id,meal_plan_id,day_number,meal_type));
CREATE TABLE shopping_lists (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), user_id TEXT NOT NULL REFERENCES users(id), meal_plan_id TEXT NOT NULL REFERENCES meal_plans(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE shopping_list_items (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), shopping_list_id TEXT NOT NULL REFERENCES shopping_lists(id), ingredient TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL, category TEXT NOT NULL, checked INTEGER NOT NULL DEFAULT 0);

CREATE TABLE events (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), user_id TEXT, session_hash TEXT, event_type TEXT NOT NULL, feature TEXT, campaign_id TEXT, metadata_json TEXT NOT NULL DEFAULT '{}', occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX events_by_creator_time ON events(creator_id,occurred_at);
CREATE TABLE affiliate_links (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), slug TEXT NOT NULL, destination_url TEXT NOT NULL, destination_host TEXT NOT NULL, campaign_id TEXT, placement TEXT, label TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(creator_id,slug));
CREATE TABLE affiliate_clicks (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), link_id TEXT NOT NULL REFERENCES affiliate_links(id), campaign_id TEXT, placement TEXT, clicked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE campaigns (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), brand TEXT NOT NULL, value_json TEXT NOT NULL, starts_at TEXT, ends_at TEXT, placements_json TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE campaign_events (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), campaign_id TEXT NOT NULL REFERENCES campaigns(id), event_type TEXT NOT NULL CHECK(event_type IN ('impression','click','interaction')), occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE revenue_events (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), source TEXT NOT NULL CHECK(source IN ('ad','affiliate','sponsor','premium','commerce')), gross_amount REAL NOT NULL, currency TEXT NOT NULL, fees REAL NOT NULL DEFAULT 0, refunds REAL NOT NULL DEFAULT 0, direct_costs REAL NOT NULL DEFAULT 0, net_amount REAL NOT NULL, campaign_id TEXT, external_transaction_id TEXT, status TEXT NOT NULL CHECK(status IN ('pending','confirmed','paid')), occurred_at TEXT NOT NULL, UNIQUE(creator_id,source,external_transaction_id));
CREATE TABLE experiments (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), feature TEXT NOT NULL, variants_json TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE experiment_assignments (creator_id TEXT NOT NULL REFERENCES creators(id), experiment_id TEXT NOT NULL REFERENCES experiments(id), user_id TEXT NOT NULL REFERENCES users(id), variant TEXT NOT NULL, assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(creator_id,experiment_id,user_id));

CREATE TABLE creator_facts (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), fact_type TEXT NOT NULL, value_json TEXT NOT NULL, source TEXT NOT NULL, source_url TEXT, retrieved_at TEXT NOT NULL, confidence REAL NOT NULL, verification_status TEXT NOT NULL CHECK(verification_status IN ('VERIFIED','INFERRED','UNKNOWN')));
CREATE TABLE research_runs (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), input_url TEXT NOT NULL, provider_results_json TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE product_opportunities (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), opportunity_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE product_specs (id TEXT PRIMARY KEY, creator_id TEXT NOT NULL REFERENCES creators(id), opportunity_id TEXT REFERENCES product_opportunities(id), spec_json TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1, review_status TEXT NOT NULL DEFAULT 'pending_review', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
