INSERT OR IGNORE INTO creators(id,slug,name,category,status,brand_json,agent_json,model_policy_json,monetization_json) VALUES
('demo-cook','anyone-can-cook-demo','Anyone Can Cook with Dr. Alisha','cooking','demo','{"accent":"#0875e1","hero":"One stop destination for all the foodies","disclaimer":"Unofficial companion for Anyone Can Cook with Dr. Alisha. Not affiliated with or endorsed by the creator."}','{"role":"cooking","promptVersion":"cooking-v1","enabledTools":["searchCreatorKnowledge","findSubstitution","calculateServings","createMealPlan","createShoppingList"]}','{"default":"STANDARD","maxCostUsd":0.05}','{"subscriptionEnabled":false,"adsEnabled":false,"affiliateEnabled":false,"sponsorshipEnabled":false,"commerceEnabled":false,"oneTimePurchaseEnabled":false}'),
('demo-second','second-creator-demo','Second Creator Demo','cooking','demo','{"accent":"#4f6958","hero":"Second kitchen","disclaimer":"Illustrative tenant for isolation testing."}','{"role":"cooking","promptVersion":"cooking-v1","enabledTools":["searchCreatorKnowledge"]}','{"default":"CHEAP","maxCostUsd":0.02}','{"subscriptionEnabled":false,"adsEnabled":false,"affiliateEnabled":false}');

INSERT OR IGNORE INTO content_sources(id,creator_id,source_type,source_url,external_id,rights_status,ingestion_status) VALUES
('sample-source','demo-cook','platform_sample','/source','sample-v1','AI_generated','complete'),
('second-source','demo-second','platform_sample','/source','second-v1','AI_generated','complete');

INSERT OR IGNORE INTO content_items(id,creator_id,source_id,external_id,source_url,title,description,content_type,structured_json,tags_json,provenance_json,rights_status) VALUES
('paneer-rice','demo-cook','sample-source','paneer-rice','/source/paneer-rice','Paneer and Pepper Rice Bowl','A quick skillet bowl using paneer, rice, peppers and warming spices. Illustrative sample, not a creator recipe.','recipe','{"minutes":25,"equipment":["stovetop"],"diet":["vegetarian","high-protein"],"servings":2,"ingredients":[{"name":"paneer","quantity":200,"unit":"g","category":"dairy"},{"name":"rice","quantity":150,"unit":"g","category":"pantry"},{"name":"bell pepper","quantity":1,"unit":"each","category":"vegetables"},{"name":"cumin","quantity":1,"unit":"tsp","category":"spices"}]}','["quick","vegetarian","high-protein","no-oven"]','{"kind":"illustrative","note":"Platform-authored sample metadata; no creator claim"}','AI_generated'),
('potato-rice','demo-cook','sample-source','potato-rice','/source/potato-rice','Golden Potato Rice Skillet','A simple one-pan idea built around potatoes, rice and onions. Illustrative sample.','recipe','{"minutes":30,"equipment":["stovetop"],"diet":["vegetarian"],"servings":2,"ingredients":[{"name":"potato","quantity":2,"unit":"each","category":"vegetables"},{"name":"rice","quantity":150,"unit":"g","category":"pantry"},{"name":"onion","quantity":1,"unit":"each","category":"vegetables"},{"name":"turmeric","quantity":0.5,"unit":"tsp","category":"spices"}]}','["budget","vegetarian","no-oven"]','{"kind":"illustrative","note":"Platform-authored sample metadata; no creator claim"}','AI_generated'),
('lentil-tiffin','demo-cook','sample-source','lentil-tiffin','/source/lentil-tiffin','Lentil Lunchbox Patties','Soft lentil and potato patties suited to a lunchbox. Check age-appropriate texture and food safety yourself. Illustrative sample.','recipe','{"minutes":35,"equipment":["stovetop"],"diet":["vegetarian","high-protein"],"servings":4,"ingredients":[{"name":"lentils","quantity":200,"unit":"g","category":"protein"},{"name":"potato","quantity":2,"unit":"each","category":"vegetables"},{"name":"onion","quantity":1,"unit":"each","category":"vegetables"}]}','["kids/tiffin","vegetarian","high-protein","no-oven"]','{"kind":"illustrative","note":"Platform-authored sample metadata; no creator claim"}','AI_generated'),
('chickpea-wrap','demo-cook','sample-source','chickpea-wrap','/source/chickpea-wrap','Creamy Chickpea Wraps','A lunch idea with chickpeas, yogurt and crunchy vegetables. Illustrative sample.','recipe','{"minutes":20,"equipment":[],"diet":["vegetarian","high-protein"],"servings":2,"ingredients":[{"name":"chickpeas","quantity":250,"unit":"g","category":"protein"},{"name":"yogurt","quantity":100,"unit":"g","category":"dairy"},{"name":"cucumber","quantity":1,"unit":"each","category":"vegetables"},{"name":"tortilla","quantity":2,"unit":"each","category":"pantry"}]}','["quick","kids/tiffin","vegetarian","no-oven"]','{"kind":"illustrative","note":"Platform-authored sample metadata; no creator claim"}','AI_generated'),
('tomato-pasta','demo-cook','sample-source','tomato-pasta','/source/tomato-pasta','Weeknight Tomato Pasta','Tomatoes, pasta and beans make a practical family dinner. Illustrative sample.','recipe','{"minutes":25,"equipment":["stovetop"],"diet":["vegetarian"],"servings":4,"ingredients":[{"name":"pasta","quantity":400,"unit":"g","category":"pantry"},{"name":"tomato","quantity":4,"unit":"each","category":"vegetables"},{"name":"white beans","quantity":250,"unit":"g","category":"protein"}]}','["quick","vegetarian","no-oven"]','{"kind":"illustrative","note":"Platform-authored sample metadata; no creator claim"}','AI_generated'),
('airfryer-potatoes','demo-cook','sample-source','airfryer-potatoes','/source/airfryer-potatoes','Crispy Air Fryer Potatoes','A simple air-fryer side with potatoes and paprika. Illustrative sample.','recipe','{"minutes":25,"equipment":["air fryer"],"diet":["vegetarian"],"servings":2,"ingredients":[{"name":"potato","quantity":3,"unit":"each","category":"vegetables"},{"name":"paprika","quantity":1,"unit":"tsp","category":"spices"}]}','["air fryer","vegetarian"]','{"kind":"illustrative","note":"Platform-authored sample metadata; no creator claim"}','AI_generated'),
('second-only','demo-second','second-source','second-only','/source/second-only','Second Creator Secret Dish','Tenant isolation sentinel.','recipe','{"minutes":10,"equipment":[],"diet":[],"servings":1,"ingredients":[{"name":"mango","quantity":1,"unit":"each","category":"vegetables"}]}','[]','{"kind":"illustrative"}','AI_generated');

INSERT OR IGNORE INTO agents(id,creator_id,role,instructions,prompt_version,model_policy,memory_policy,safety_policy) VALUES
('demo-cooking-agent','demo-cook','cooking','Ground suggestions in allowed creator content. Label AI suggestions. Never invent creator statements.','cooking-v1','STANDARD','adult-preferences-only','no-medical-or-allergy-assurances');
INSERT OR IGNORE INTO agent_tools(creator_id,agent_id,tool_name) VALUES
('demo-cook','demo-cooking-agent','searchCreatorKnowledge'),('demo-cook','demo-cooking-agent','findSubstitution'),('demo-cook','demo-cooking-agent','calculateServings'),('demo-cook','demo-cooking-agent','createMealPlan'),('demo-cook','demo-cooking-agent','createShoppingList');
INSERT OR IGNORE INTO feature_gates(creator_id,feature,required_entitlement,free_usage_limit,reset_period,trial_usage,paywall_placement,enabled) VALUES
('demo-cook','AI_TEXT','premium',5,'day',0,'after_result',1),('demo-cook','AI_VOICE','premium',NULL,'lifetime',2,'after_trial',1),('demo-cook','MEAL_PLAN','premium',2,'lifetime',0,'after_preview',1),('demo-cook','SHOPPING_LIST','premium',0,'lifetime',0,'after_plan',1),('demo-cook','SAVE_CONTENT','premium',5,'lifetime',0,'after_save',1);
INSERT OR IGNORE INTO plans(id,creator_id,code,label,price_json) VALUES ('demo-free','demo-cook','free','Free','{}'),('demo-premium','demo-cook','premium','Premium','{}');
INSERT OR IGNORE INTO entitlements(id,creator_id,code,description) VALUES ('demo-premium-entitlement','demo-cook','premium','Premium cooking features');
UPDATE content_items SET structured_json=json_set(structured_json,'$.mealType','side') WHERE id='airfryer-potatoes' AND creator_id='demo-cook';
UPDATE content_items SET structured_json=json_set(structured_json,'$.mealType','lunch') WHERE id='lentil-tiffin' AND creator_id='demo-cook';
UPDATE content_items SET structured_json=json_set(structured_json,'$.mealType','lunch') WHERE id='chickpea-wrap' AND creator_id='demo-cook';
